import { BsChevronDown } from "react-icons/bs";
import { DiScrum } from "react-icons/di";
import { FaJava, FaLinkedinIn } from "react-icons/fa";
import { FiSettings } from "react-icons/fi";
import { MdHttp } from "react-icons/md";
import {
	SiArduino,
	SiC,
	SiCplusplus,
	SiCss3,
	SiDart,
	SiDocker,
	SiExpress,
	SiFlutter,
	SiGithub,
	SiGmail,
	SiGnubash,
	SiHomebrew,
	SiHtml5,
	SiInsomnia,
	SiIntellijidea,
	SiIterm2,
	SiJavascript,
	SiJson,
	SiMacos,
	SiMarkdown,
	SiMongodb,
	SiNestjs,
	SiNextdotjs,
	SiNodedotjs,
	SiNpm,
	SiPnpm,
	SiPostgresql,
	SiPostman,
	SiRaspberrypi,
	SiReact,
	SiRedux,
	SiSolid,
	SiSpringboot,
	SiTailwindcss,
	SiTypescript,
	SiVisualstudiocode,
	SiX,
	SiYarn,
} from "react-icons/si";

export const icons = {
	si: [
		SiTypescript,
		SiJavascript,
		SiDart,
		SiCplusplus,
		SiC,
		SiGnubash,
		SiNodedotjs,
		SiExpress,
		SiReact,
		SiSolid,
		SiNextdotjs,
		SiNestjs,
		SiJson,
		SiFlutter,
		SiMongodb,
		SiPostgresql,
		SiRedux,
		SiHtml5,
		SiCss3,
		SiTailwindcss,
		SiRaspberrypi,
		SiArduino,
		SiHomebrew,
		SiDocker,
		SiIterm2,
		SiInsomnia,
		SiPostman,
		SiIntellijidea,
		SiVisualstudiocode,
		SiMarkdown,
		SiNpm,
		SiGithub,
		SiPnpm,
		SiYarn,
		SiMacos,
		SiX,
		SiGmail,
		SiSpringboot,
	],
	fa: [FaJava, FaLinkedinIn],
	md: [MdHttp],
	fi: [FiSettings],
	di: [DiScrum],
	bs: [BsChevronDown],
};
