/* global require, module */
// @ts-check

const {
  SiTypescript,
  SiJavascript,
  SiDart,
  SiCplusplus,
  SiC,
  SiGnubash,
  SiNodedotjs,
  SiExpress,
  SiReact,
  SiSolid,
  SiNextdotjs,
  SiNestjs,
  SiJson,
  SiFlutter,
  SiMongodb,
  SiPostgresql,
  SiRedux,
  SiHtml5,
  SiCss3,
  SiTailwindcss,
  SiRaspberrypi,
  SiArduino,
  SiHomebrew,
  SiDocker,
  SiIterm2,
  SiInsomnia,
  SiPostman,
  SiIntellijidea,
  SiVisualstudiocode,
  SiMarkdown,
  SiNpm,
  SiPnpm,
  SiYarn,
  SiMacos,
  SiTwitter,
  SiGmail,
} = require('react-icons/si');
const { FaJava, FaLinkedinIn } = require('react-icons/fa');
const { GoMarkGithub } = require('react-icons/go');
const { MdHttp } = require('react-icons/md');
const { FiSettings } = require('react-icons/fi');

const icons = {
  si: [
    SiTypescript,
    SiJavascript,
    SiDart,
    SiCplusplus,
    SiC,
    SiGnubash,
    SiNodedotjs,
    SiExpress,
    SiReact,
    SiSolid,
    SiNextdotjs,
    SiNestjs,
    SiJson,
    SiFlutter,
    SiMongodb,
    SiPostgresql,
    SiRedux,
    SiHtml5,
    SiCss3,
    SiTailwindcss,
    SiRaspberrypi,
    SiArduino,
    SiHomebrew,
    SiDocker,
    SiIterm2,
    SiInsomnia,
    SiPostman,
    SiIntellijidea,
    SiVisualstudiocode,
    SiMarkdown,
    SiNpm,
    SiPnpm,
    SiYarn,
    SiMacos,
    SiTwitter,
    SiGmail,
  ],
  fa: [FaJava, FaLinkedinIn],
  go: [GoMarkGithub],
  md: [MdHttp],
  fi: [FiSettings],
};

module.exports = { icons };
