#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

bun biome ci .

BRANCH="$(git rev-parse --abbrev-ref HEAD)"

if (git diff --name-only origin/"$BRANCH" HEAD | grep -qvE '^(README\.md|(biome|vercel)\.json|(\.vscode|\.github|\.husky|scripts|server)/.*)$'); then
  bun run build
else
  echo "Skipping 'bun run build'"
fi

if (git diff --quiet --name-only origin/"$BRANCH" HEAD server); then
  echo "Skipping server 'make audit'"
else
  cd server && make audit
fi
