#!/bin/sh

if (git diff --name-only --staged | grep -qvE '^(README\.md|(biome|vercel)\.json|(\.vscode|\.github|\.husky|scripts|server)/.*)$'); then
  bun biome ci .
else
  echo "Skipping 'biome ci'"
fi

if (git diff --quiet --name-only --staged server); then
  echo "Skipping server 'make tidy'"
else
  cd server && make tidy
fi
