#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

bun biome ci .

git diff --name-only HEAD^ HEAD | grep --quiet --invert-match --extended-regexp '^README\\.md|(biome|vercel)\\.json|(\\.vscode|\\.github|\\.husky|scripts|server)/.*$' || bun run build
