#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

bun biome ci .

(
  ! git diff --name-only origin/"$(git rev-parse --abbrev-ref HEAD)" HEAD |
    grep --quiet --invert-match --extended-regexp '^README\\.md|(biome|vercel)\\.json|(\\.vscode|\\.github|\\.husky|scripts|server)/.*$'
) &&
  bun run build ||
  echo "Skipping 'bun run build'"

(
  ! git diff --quiet --name-only origin/"$(git rev-parse --abbrev-ref HEAD)" HEAD server
) &&
  (cd server && make audit) ||
  echo "Skipping server 'make audit'"
